"""user_corrections

Revision ID: d8748ec39af9
Revises: 9cf9c9036ce9
Create Date: 2024-01-20 13:26:16.172385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8748ec39af9'
down_revision: Union[str, None] = '9cf9c9036ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
